export const messages = {
        "welcome":"Hi 🙂🖐 i'm Sparco Please can i have your name ? ",
        "cost": "At Sparc it cost 2000rs for the first month and then 800 rs after the first month",
        "location":"At flic en flac a map can be provided if you want one (Do you wish to view map (yes/no))",
        "activity":"At the Sparc we have the following as activities:\n1- Basketball\n2- 50m swimming pool\n3- Lawn tennis\n4- Soccer pitch standard\n5- And a 6 aside pictch",
        "basketball":  "Basketball 🏀 is played on the following days and time:\nMonday (12:00pm - 15:00pm)\nWednesday (08:00am - 11:00am)" ,     
        "soccer":  "Soccer ⚽ is played on the following days and time:\n Tuesday (12:00pm - 15:00pm)\Friday (08:00am - 11:00am)",
        "tennis":  "Tennis 🎾 is played on the following days and time:\n Tuesday (12:00pm - 15:00pm)\Friday (08:00am - 11:00am)",
        "Swimming": "Swimming 🏊‍♂️ is done on the following days and time:\n Saturday (12:00pm - 15:00pm)\nSunday (08:00am - 11:00am)\nNB: Only if it's sunny ☀️",
        "appreciation": "🙂 Sparco always available for you",
        "closing":"👋 Thanks for using Sparco"
}


export const words = {
    "registration": "cost",
    "cost":"cost",
    "fee":"cost",
    "price":"cost",
    "Where":"location",
    "located":"location",
    "location":"location",
    "map":"location",
    "distance":"location",
    "area":"location",
    "region":"location",
    "city":"location",
    "activities":"activity",
    "activity":"activity",
    "leisure":"activity",
    "entertainment":"activity",
    "games":"activity",
    "football":"activity",
    "basketball":"activity",
    "swimming":"activity",
    "pool":"activity",
    "soccer":"activity",
    "gym":"activity",
    "tennis":"activity",
    "tenis":"activity",
    "thanks":"appreciation",
    "thank":"appreciation",
    "bye":"closing",
}
